### ISSUE TITLE
Backspace in Insert mode only deletes from one cursor  

### ISSUE THREAD

**Issue by JeppeLS** [brenton-leighton/multiple-cursors.nvim#24]
When i press backspace in insert mode, the deletion only happen on my most recently added cursor, instead of all cursors.
I'm on nvim v0.9.4

Here is a small example showing what i mean. 
[Screencast from 2023-12-21 08-25-48.webm](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/33690886/2a75ffd0-2029-455c-8c0d-5876a7186607)

**Comment by brenton-leighton** [comment]
Are you using the autopairs plugin? If not, can you tell me the output of this command:

```
:lua vim.print(vim.inspect(vim.fn.maparg("<Backspace>", "i", false, false)))
```

**Comment by jls-ceptu** [comment]
Yes I am.

Are thus plugin and autopairs incompatible? If so I'll just disable the autopairs plugin.

**Comment by jls-ceptu** [comment]
I saw this is probably a duplicate of #3. So this can be closed.

**Comment by erlonbie** [comment]
Same issue, mine is:

v:lua.MPairs.autopairs_bs() 

I seted the `pre_hook` and `post_hook` to disable autopairs plugin.

``` lua
pre_hook = function()
	require('nvim-autopairs').disable()
end,

post_hook = function()
	require('nvim-autopairs').enable()
end,
```

**Comment by brenton-leighton** [comment]
> Same issue, mine is:
> 
> v:lua.MPairs.autopairs_bs()

Can you show the output of the command before and after creating cursors? You could also use `:verbose imap <BS>` to print the mapping.

**Comment by brenton-leighton** [comment]
Also can you make sure nvim_autopairs is up to date? I don't think they use the MPairs global variable anymore.

It might be causing an issue that means multiple-cursors.nvim can't override the mapping.

**Comment by brenton-leighton** [comment]
@erlonbie I just realised I probably need to address you to notify you of a response

**Comment by erlonbie** [comment]
I just updated both plugins and the problem is gone, thank you! sorry for the miss report

**Comment by brenton-leighton** [comment]
No worries
