### ISSUE TITLE
Minipairs not correctly disabled despite using hooks

### ISSUE THREAD

**Issue by JoshBenn** [brenton-leighton/multiple-cursors.nvim#44]
Check this [video](https://youtu.be/QKnqoOMp_zs) to see it in action

Issue:
- When in insert mode and typing any opening paired item (e.g. `[, {, ", (`), the main cursor will act normally while the remaining cursors will print only the closing paired item.

Context:
- Nvim nightly
- wsl environment
- MC opts:
![image](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/134667610/d7d0f95d-ff53-46d7-9105-0d5ec3ee04b8)
- Plugins:
![image](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/134667610/b0b5800c-301c-45c7-bbc5-236b4df2586d)

Mini-pairs are in a default configuration as listed on their GitHub.

**Comment by brenton-leighton** [comment]
It looks like you've put the `pre_hook` and `post_hook` functions are in the `custom_key_maps` table.

**Comment by JoshBenn** [comment]
> It looks like you've put the `pre_hook` and `post_hook` functions are in the `custom_key_maps` table.

That would resolve the issue, thanks!
