### ISSUE TITLE
feat: preserve selection when creating cursors from visual mode

### ISSUE THREAD

**Issue by b0o** [brenton-leighton/multiple-cursors.nvim#51]
For example, in this scenario:

https://github.com/brenton-leighton/multiple-cursors.nvim/assets/21299126/a393e2c8-0397-4de2-8ad3-1f19bf3fad3f

It would be nice if each subsequent cursor maintained the visual selection of `ipsum`.

**Comment by brenton-leighton** [comment]
You're using the search command (`MultipleCursorsAddMatches`) to add the cursors, right?

**Comment by b0o** [comment]
In the screencast above, I was creating a visual selection and then using `MultipleCursorsAddDown`.

 It would be nice if it worked in both `MultipleCursorsAddDown` and `MultipleCursorsAddMatches`

**Comment by brenton-leighton** [comment]
OK I think I can do that.

**Comment by brenton-leighton** [comment]
I think this should do it: #54.

Let me know if it's OK.
