### ISSUE TITLE
multiple cursor doesnt work way its supposed to be 

### ISSUE THREAD

**Issue by bozkayasalihx** [brenton-leighton/multiple-cursors.nvim#64]
* MultipleCursorJumpNextMatch supposed to be jump next match but its follows up from a previous char in visual mode
* i think it doest get last char in matched string

BTW thanks for this awesome plugin

**Comment by brenton-leighton** [comment]
Hey, thanks. I'm not sure exactly what you're describing, could you post a video?

**Comment by brenton-leighton** [comment]
I'm going to close this issue if there's no reply. I have occasionally seen weird behaviour when adding cursors in visual mode, but I can't replicate it and don't know exactly why it happened.
