### ISSUE TITLE
Multiple Cursors with delete line and then paste line

### ISSUE THREAD

**Issue by danrasmuson** [brenton-leighton/multiple-cursors.nvim#66]
I'm trying to reproduce the behavior as found in sublime and vscode.

![CleanShot 2024-05-29 at 11 09 06](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/4013767/cd10c8c8-fd1b-48f9-a3f3-27b699b1b50f)

But when I try with this extension it seems like multiple cursors don't work when the group on top of each other such as after commands like `G` in normal mode

![CleanShot 2024-05-29 at 11 14 03](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/4013767/d2cb0219-97f5-452b-86ac-f4000251be72)

Any help here is appreciated!

**Comment by brenton-leighton** [comment]
At the moment the registers for the virtual cursors are just lost on exit. I'll write something to concatenate them into the real cursor register on exit. Thanks.

**Comment by danrasmuson** [comment]
Ahh. Yes.  Your right. That is needed. 

The other issue is that when "G" was pressed only one cursor and not the other

**Comment by brenton-leighton** [comment]
> The other issue is that when "G" was pressed only one cursor and not the other

`G` isn't implemented, but making it a special function that moves all cursors to the end lines of the buffer sounds like a good idea. Something similar would work for `gg` too.

**Comment by brenton-leighton** [comment]
I've implemented merging the registers in #68. Let me know if it's OK.

I've also created a issue #67 for adding the `G` and `gg` commands.

Thanks

**Comment by danrasmuson** [comment]
Yes confirmed! Thank you very much @brenton-leighton.
