### ISSUE TITLE
feat: Public a function `add_cursor(row, col)` to add cursor in customized way

### ISSUE THREAD

**Issue by mrbeardad** [brenton-leighton/multiple-cursors.nvim#7]
Public a function `add_cursor(row, col)` to add cursor in customized way, such as `flash.nvim`

**Comment by brenton-leighton** [comment]
I've added a new function in the [feat_add_cursor](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/feat_add_cursor) branch. The signature is `add_cursor(lnum, col, curswant)`. Is that OK?

**Comment by mrbeardad** [comment]
Maybe a seperate `init()` is required, because keymap set is too early.

**Comment by mrbeardad** [comment]
You could take a look at this plugin [vscode-multi-cursor.nvim](https://github.com/vscode-neovim/vscode-multi-cursor.nvim#flash-integration)

**Comment by brenton-leighton** [comment]
> Maybe a seperate `init()` is required, because keymap set is too early.

Do you get an error? Is there a problem with settings key maps when add_cursor is called?

**Comment by mrbeardad** [comment]
> > Maybe a seperate `init()` is required, because keymap set is too early.
> 
> Do you get an error? Is there a problem with settings key maps when add_cursor is called?

No, I mean, keymap set too earl that I can't type letters to choose label in flash, I need to init keymaps manually

**Comment by brenton-leighton** [comment]
I'm not sure how flash.nvim works, and I haven't looked much at how this plugin integrates with other plugins. Is there anyway you can create the cursors after choosing labels?

**Comment by mrbeardad** [comment]
Yes, flash.nvim allow you to search for pattern, and display labels for user to press and jump, (like hop and easymotion).
And it provide a hook function to do something when user input a label, for me, I want add a cursor at label position that have choosed

**Comment by mrbeardad** [comment]
> Otherwise is there a way you can save the new cursor positions somewhere, then add them all at once?
Sounds like a good idea
