### ISSUE TITLE
Not loaded by lazy, even with "lazy = false", "event = "VeryLazy"" and so son

### ISSUE THREAD

**Issue by hrqmonteiro** [brenton-leighton/multiple-cursors.nvim#73]
The plugin is not loaded by lazy.vim, therefore i cannot use it

![image](https://github.com/user-attachments/assets/2fbe2073-b11c-427c-bb24-eb054432f53f)
![image](https://github.com/user-attachments/assets/b4633f0a-cc72-45c4-9603-4463b6f84dc1)

**Comment by brenton-leighton** [comment]
I don't know why that's happening. Can you try disabling all other plugins to see if it still doesn't load?

**Comment by EricDriussi** [comment]
Chiming in to point out two things:
1. A plugin not being loaded by one plugin manager is hardly an issue with the plugin.
1. I can confirm that the plugin works as expected and is loaded by Lazyvim (so lazy.nvim) with the config that OP provided.

I would consider this user error and close the issue.

**Comment by 4frag** [comment]
i had similar issue
it's cause i forgot to add config for multiple-cursors:
```
-- Multiple cursors
{
    'brenton-leighton/multiple-cursors.nvim',

    config = function()
        require('multiple-cursors').setup {}
    end,

    keys = {
        {"<C-Up>", "<Cmd>MultipleCursorsAddUp<CR>", mode = {"n", "i", "x"}, desc = "Add cursor and move up"},
        {"<C-Down>", "<Cmd>MultipleCursorsAddDown<CR>", mode = {"n", "i", "x"}, desc = "Add cursor and move down"},
    },
},
```
