### ISSUE TITLE
Normal mode not match the whole word.

### ISSUE THREAD

**Issue by milkpuff** [brenton-leighton/multiple-cursors.nvim#78]
![图片](https://github.com/user-attachments/assets/b5538e18-5ba8-4524-aa7f-ba61b7c63d5d)
In normal mode, I put cursor at 'is', and then match next to 'this', and then match next to 'this'
In this case, my intention is to match the whole word 'is', not 'is' in 'this'.
Normal mode match next should match the whole word. Visual mode should match the selected. SublimeText and VSCode 'ctrl+d' runs like this logic. 

To fix this is simple. Just add one line to `function get_search_pattern()` to match the whole word in normal mode. 

```diff
--- a/lua/multiple-cursors/init.lua
+++ b/lua/multiple-cursors/init.lua
@@ -600,6 +600,7 @@ local function get_search_pattern()
     pattern = get_visual_area_text()
   else -- Normal mode
     pattern = vim.fn.expand("<cword>")
+    pattern = "\\<" .. vim.pesc(pattern) .. "\\>"
   end
 
   if pattern == "" then
```

**Comment by brenton-leighton** [comment]
Thanks for that. Added in #80.
