### ISSUE TITLE
bug: Cursors have wrong positions when escape at start of the line.

### ISSUE THREAD

**Issue by mrbeardad** [brenton-leighton/multiple-cursors.nvim#9]
Cursor shouldn't move left when escape at start of the line.

[multiple-cursor-bug.webm](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/54128430/993e6dc2-ab31-439d-b5a2-41e16efa0280)

**Comment by brenton-leighton** [comment]
Does this fix it: [fix_exiting_insert_mode](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/fix_exiting_insert_mode)?

**Comment by brenton-leighton** [comment]
Do you have a setting enabled that allows the `h` command to change lines?

**Comment by mrbeardad** [comment]
> Does this fix it: [fix_exiting_insert_mode](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/fix_exiting_insert_mode)?

Yes, thanks for it.

> Do you have a setting enabled that allows the `h` command to change lines?

Yes.
